name: Paradayish
description: A constantly evolving far-fetched story, with regular (daily/weekly) installments
permalink: /:year/:month/:day/:title.html
url: http://retrodans.github.io/paradayish/
excerpt_separator: <!--more-->